### PR TITLE
Added custom css and fonts

### PR DESCRIPTION
**Pull request by saariokari-xx**

### CODE REVIEW

**Comment by jaakkokorhonen** [comment]
@gvilarino Francesca is asking if this is going to be merged into Guanyem aswell?

**Comment by gvilarino** [comment]
I believe this will make sense to be pushed to Guanyem _after_ they've finished the actual pilot; the tool is still live and a design change right now isn't probably for the best.

**Comment by jaakkokorhonen** [comment]
Sure, maybe push it to finnish-democracyos for review?

**Comment by gvilarino** [comment]
That or democracyos-dcent.herokuapp.com, as you prefer

**Comment by jaakkokorhonen** [comment]
good point, both i should think. did you test it already @gvilarino

**Comment by gvilarino** [comment]
Haven't had time yet; will do these next couple of days.

**Comment by jaakkokorhonen** [comment]
ok @gvilarino so where are we with this?

**Comment by gvilarino** [comment]
I'm addressing this right now

**Comment by gvilarino** [comment]
Ok guys this is merged. You can check out the live demo either in [english](democracyos-dcent.herokuapp.com) or in [finnish](http://finnish-democracyos.herokuapp.com/).

Great work @jayapapaya @jaakkokorhonen and the rest! Sorry this took so long.

**Comment by gvilarino** [comment]
@jaakkokorhonen the [latest PR](https://github.com/d-cent/democracyos/pull/59) is now merged and deployed to [the live demo](http://democracyos-dcent.herokuapp.com)

Should I update the finnish version as well?

**Pull request merged**
